### ISSUE TITLE
How to edit VSCode's title bar to have the menu in it

### ISSUE THREAD

**Issue by sortedcord** [Vista1nik/i3-winter2020#1]
I suppose I have installed the theme properly and the everything works, including compton and pico. But I couldn't get VSCode to look like that. How did u do that?

**Comment by Vista1nik** [comment]
You need to install [lxappearance](https://www.archlinux.org/packages/community/x86_64/lxappearance/), then change your GTK theme to [arc-dark](https://github.com/horst3180/arc-theme) and set gtk font to cascadia code.
![image](https://user-images.githubusercontent.com/16061243/101022094-f9077180-3581-11eb-89ef-59072356bc4f.png)

Also you need to set `"window.titleBarStyle": "custom",` in your VSCode settings.
